
services:
  logger:
    build: ./logger
    container_name: logger
    volumes:
      - logs:/logs

  app:
    build: ./app
    container_name: app
    ports:
      - "7000:7000"
    volumes:
      - logs:/logs

volumes:
  logs:
